version: '3.7'
services:
    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres_test
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
        logging:
            options:
                max-size: 10m
                max-file: '3'
        ports:
            - '5432:5432'
        expose:
            - 5432
        volumes:
            # copy the sql script to create tables
            - ./schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
